<?xml version="1.0" encoding="utf-8"?><Database Name="AMZ-Coupon" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=KUODAVID;Initial Catalog=AMZ-Coupon;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AMZ_CouponConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Coupon" Member="Coupon">
    <Type Name="Coupon">
      <Column Name="CouponID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Coupon" Member="Coupon1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Valid" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MemberID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Association Name="Coupon_Product" Member="Product" ThisKey="CouponID" OtherKey="CouponID" Type="Product" />
      <Association Name="Member_Coupon" Member="Member" ThisKey="MemberID" OtherKey="MemberID" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Member" Member="Member">
    <Type Name="Member">
      <Column Name="MemberID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="passwrod" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Manager" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Member_Coupon" Member="Coupon" ThisKey="MemberID" OtherKey="MemberID" Type="Coupon" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Product">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Shelf" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CouponID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Coupon_Product" Member="Coupon" ThisKey="CouponID" OtherKey="CouponID" Type="Coupon" IsForeignKey="true" />
    </Type>
  </Table>
</Database>